seed: 1
model: 'SPACE'
resume: true
load_time_consistency: false
resume_ckpt: pretrained/atari_joint.pth
# 'output/checkpoints/atari_mspacman/model_000079001.pth'
parallel: true
device_ids: [2, 3, 4, 5, 6, 7]
device: 'cuda:2'

logdir: 'output/logs'
checkpointdir: 'output/checkpoints'
evaldir: 'output/eval'

dataset: 'ATARI'
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  #ATARI: '../data/ATARI'
  ATARI: 'aiml_atari_data/space_like'


train:
  batch_size: 36
  max_epochs: 100
  max_steps: 1600000
  print_every: 100
  save_every: 500
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: false
  solver:
    fg:
      optim: 'RMSprop'
      lr: 1e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

arch:
  G: 16
  fg_sigma: 0.20

  z_pres_start_step: 10000
  z_pres_end_step: 15000
  z_pres_start_value: 0.1
  z_pres_end_value: 1e-10

  z_scale_mean_start_step: 0
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -2.0
  z_scale_mean_end_value: -2.5

  tau_start_step: 0
  tau_end_step: 10000
  tau_start_value: 2.5
  tau_end_value: 2.5

  fix_alpha_steps: 4000
  fix_alpha_value: 0.1

  K: 3
  bg_sigma: 0.10
  boundary_loss: false

gamelist: [
    # 'Atlantis-v0',
    # 'Asterix-v0',
    # 'Carnival-v0',
    # 'DoubleDunk-v0',
    # 'Kangaroo-v0',
    # 'MontezumaRevenge-v0',
    'MsPacman-v0',
    # 'Pooyan-v0',
    # 'Qbert-v0',
    # 'SpaceInvaders-v0',
    ]
