env_name: 'PongDeterministic-v4'

device: 'cuda:0'
parallel: False

train:
  batch_size: 128
  gamma: 0.97
  eps_start: 1.0
  eps_end: 0.01
  eps_decay: 100000
  learning_rate: 0.0002

  memory_size: 50000
  memory_min_size: 2500

  num_episodes: 1000
  max_steps: 100000

  skip_frames: 1
  
  log_steps: 500
  # save every is for episodes
  save_every: 5

