env_name: 'TennisDeterministic-v4'

device: 'cuda:0'
parallel: False

logdir: '/xrl/relogs/'

video_steps: 100

train:
  gamma: 0.97
  learning_rate: 0.0001

  num_episodes: 50000
  max_steps: 100000
  
  log_steps: 25
  # save every is for episodes
  save_every: 25

  hidden_layer_size: 64