env_name: 'PongDeterministic-v4'

device: 'cuda:0'
parallel: False

logdir: '/xrl/logs/'

video_steps: 100

train:
  num_episodes: 50000
  max_steps: 100000
  
  log_steps: 500
  # save every is for episodes
  save_every: 100000


