env_name: 'TennisDeterministic-v4'

rl_algo: 2

device: 'cuda:0'
parallel: False

logdir: '/xrl/genlogs/'

video_steps: 100

raw_image: True

train:
  num_episodes: 50000
  max_steps: 50000
  
  log_steps: 500


